### ISSUE TITLE
Is this ok to use Entity inside a Data layer?

### ISSUE THREAD

**Issue by tdasarun** [mimamch/news_app_clean_architecture#1]
https://github.com/mimamch/news_app_clean_architecture/blob/7fc75f95288ddb05bbc587ea37a01e7ca2acc9c5/lib/features/news/data/api/news_api.dart#L8

**Comment by mimamch** [comment]
Thank you for asking,

Looks like we should use Models or DTO instead of Entity


This on development branch maybe related with that issue

https://github.com/mimamch/news_app_clean_architecture/blob/1a0e0361d537f34b5a7f843e31d403335b24ee76/lib/features/post/data/datasources/post_api.dart#L14C2-L14C2
